KS-1-2
AntonYakushenko/KotlinSprint pull request #2
Opened 2023-07-18 19:52 UTC by AntonYakushenko

output to the console the values of all previously declared variables
declared a new variable employeeCount
comment variable employeeCount
declared a new variable newEmployeeCount

2023-07-18 21:58 UTC, ievetrov requested changes
оставил коммент для правок. нужно переключиться в эту ветку, сделать коммит с правками и снова отправить в бот ссылку на этот пулл реквест

2023-07-18 21:58 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_2.kt
> +    val newEmployeeCount: Int = 1999
согласно ТЗ нужно именно перезаписать предыдущую переменную, без создания новой

2023-07-19 10:20 UTC, AntonYakushenko commented on src/main/kotlin/lesson_1/lesson_1_task_2.kt
> +    val newEmployeeCount: Int = 1999
исправил

2023-07-19 19:28 UTC, ievetrov approved these changes
ок!

2023-07-20 03:04 UTC, merged