KS-1-3 declared a new variables and print them
AntonYakushenko/KotlinSprint pull request #3
Opened 2023-07-18 20:17 UTC by AntonYakushenko

2023-07-18 21:59 UTC, ievetrov requested changes

2023-07-18 21:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour: Int = 9
в целом результат есть) но в примере в ТЗ цифры начинаются с 0
вообще нормальная практика, если сервер присылает дату или время строкой.
давай объявим строки и сделаем правильный формат)

2023-07-19 10:46 UTC, AntonYakushenko commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour: Int = 9
исправил

2023-07-19 19:28 UTC, ievetrov approved these changes
все так

2023-07-20 03:04 UTC, merged