KS-1-5 Declared a variable with the number of seconds Gagarin spent in space and output in different formats.
AntonYakushenko/KotlinSprint pull request #5
Opened 2023-07-18 20:39 UTC by AntonYakushenko

2023-07-18 22:00 UTC, ievetrov requested changes

2023-07-18 22:00 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("${String.format("%02d", hours)}:${String.format("%02d", minutes)}:${String.format("%02d", seconds)}")
хорошо! но в String.format() можно поместить сразу все параметры

2023-07-19 10:30 UTC, AntonYakushenko commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("${String.format("%02d", hours)}:${String.format("%02d", minutes)}:${String.format("%02d", seconds)}")
исправил

2023-07-19 19:27 UTC, ievetrov approved these changes
отлично, все красиво)

2023-07-20 03:05 UTC, merged